---

namespace: chris93111

name: nats_eda

version: 1.0.0

readme: README.md

authors:
  - FERREIRA Christophe <christopheferreira@cnaf.fr>

description: Event Driven Automation with Nats/Jetstream

license_file: 'LICENSE'

tags:
  - eda
  - ansible
  - events
  - nats

# dependencies:

repository: https://github.com/chris93111/nats.eda

documentation: https://github.com/chris93111/nats.eda.git

issues: https://github.com/chris93111/nats.eda.git/issues

build_ignore: []